networks:
  dockernetwork:
    external: true
services:
  traefik:
    image: traefik
    hostname: traefik
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    networks:
      dockernetwork:
        ipv4_address: 172.28.1.2
    ports:
      # - 80:80
      - 443:443
    volumes:
      - ./configs/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./configs/config.yml:/config.yml:ro
      - ./configs/acme.json:/acme.json
      - ./configs/logs:/logs
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Asia/Kolkata
      CF_DNS_API_TOKEN_FILE: $CF_TOKEN
    restart: unless-stopped
